#    Numpy Arrays

In [64]:
my_list = [1,2,3]
import numpy as np 
arr = np.array(my_list)
arr

array([1, 2, 3])

In [65]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]] #Creates array matrix from list of lists
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.arange(0,11,) #creates 1D array from low to high excluding

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
np.arange(0,11,2) #Returns Integers - Takes step size = 2

array([ 0,  2,  4,  6,  8, 10])

In [68]:
np.zeros(3) #1D Vector

array([0., 0., 0.])

In [69]:
np.zeros((2,2)) #2D Matrix

array([[0., 0.],
       [0., 0.]])

In [70]:
np.ones(3)

array([1., 1., 1.])

In [71]:
np.ones((3,3)) #Unity Matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.linspace(0,5,10) #Returns one dimenstional array of 10 evenly spaced number between 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [73]:
np.eye(4) # Returns an Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
np.random.rand(5) #Returns a 1D array of random numbers uniformly distributed between 0 to 1

array([0.3872432 , 0.68575213, 0.88634597, 0.68042128, 0.47776322])

In [75]:
np.random.rand(5,5) #Returns a 5*5 Matrix of uniformly distributed random numbers

array([[0.41809089, 0.45511819, 0.30045173, 0.62950824, 0.00140808],
       [0.71819733, 0.36128804, 0.45475683, 0.36411452, 0.97918129],
       [0.85978056, 0.13991598, 0.89101421, 0.03290356, 0.17430774],
       [0.90566244, 0.93147674, 0.4531368 , 0.11048407, 0.49249263],
       [0.52074395, 0.93248058, 0.32819498, 0.65912074, 0.33658225]])

In [76]:
np.random.randn(5) #Returns a standard normal/gaussian distribution centered around zero

array([-0.2279478 ,  1.33271256, -0.24685415, -1.29015249, -1.45138042])

In [77]:
np.random.randn(4,4) #Returns 4*4 Matrix of Standard Normal Dist. Centered around Zero

array([[ 0.09686185,  0.65981409,  1.38877747, -1.01253274],
       [ 0.50781732,  0.99395   , -0.65460801,  1.743977  ],
       [-0.42972207,  1.18100988,  0.063018  ,  1.89321951],
       [-0.34053032,  0.2478873 ,  0.30740329,  1.43302667]])

In [78]:
np.random.randint(1,100,10) #returns a random integer between low and high value(excluded). 
#Giving a third argument determines number of integers returned

array([94, 51,  2, 90, 46, 82, 33, 57, 29, 85])

In [79]:
arr = np.arange(25)
arr
ranarr = np.random.randint(0,50,10)
ranarr

array([ 1,  7, 40, 47, 22, 49, 16, 13, 41, 18])

In [80]:
#Reshaping Array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
ranarr.reshape(2,5)

array([[ 1,  7, 40, 47, 22],
       [49, 16, 13, 41, 18]])

In [82]:
ranarr.reshape(5,2)

array([[ 1,  7],
       [40, 47],
       [22, 49],
       [16, 13],
       [41, 18]])

In [83]:
ranarr.max()

49

In [84]:
ranarr.min()

1

In [85]:
ranarr.argmax() #Locates index location of max value

5

In [86]:
ranarr.argmin() #Locates index location of min value

0

In [87]:
arr.shape #1D #Shape is an Attribute of class array not a method

(25,)

In [88]:
arr.reshape(5,5).shape #5*5 Shape 2D Matrix

(5, 5)

In [89]:
arr.dtype #dType is an attribute of class array not a method

dtype('int64')

In [0]:
from numpy import *

In [91]:
random.randint(0,11,2)

array([3, 2])

In [0]:
import numpy as np

Numpy Indexing and Selection

In [93]:
arr = np.arange(0,11) #11 elements from 0 to 10
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[0]

0

In [95]:
arr[1:4]

array([1, 2, 3])

In [96]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [97]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [98]:
arr[0:5] = 100 #Broadcast the value 100 to 1st 5 elements
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [99]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [101]:
arr1 = slice_of_arr[:] # They are the same objects
arr1[:] = 10
arr1
slice_of_arr
arr1 == slice_of_arr

array([ True,  True,  True,  True,  True,  True])

In [102]:
arr1 = slice_of_arr.copy() #Copy object not same
arr1[:] = 4
arr1
slice_of_arr
arr1 == slice_of_arr

array([False, False, False, False, False, False])

#Indexing 2D Array/Matrix

In [103]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
#Double Bracket Format
arr_2d[0][0] #Returns digit in first row and first column 

5

In [105]:
arr_2d[0] #Retuns the entire first row. [R][C]

array([ 5, 10, 15])

In [106]:
arr_2d[1][1]
arr_2d[2][1]

40

In [107]:
#Single Bracket Notation [R,C]
arr_2d[1,2]

30

In [108]:
#Subsetting
arr_2d[1:,1:]
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [109]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [110]:
arr_2d[:,:1]

array([[ 5],
       [20],
       [35]])

#Condtional Selection

In [111]:
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [112]:
arr > 5 #Retruns boolean values for each comparision case

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [113]:
bool_arr = arr>5
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [114]:
arr[bool_arr]

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [115]:
#do in one step
arr[arr>8]

array([10, 10, 10, 10, 10, 10,  9, 10])

In [116]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [117]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

Numpy Array Operations

In [118]:
#Array with Array
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [119]:
arr + arr

array([20, 20, 20, 20, 20, 20, 12, 14, 16, 18, 20])

In [120]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [121]:
arr * arr

array([100, 100, 100, 100, 100, 100,  36,  49,  64,  81, 100])

In [122]:
#arr with scalar
arr + 100 #adds 100 to every element in the array 

array([110, 110, 110, 110, 110, 110, 106, 107, 108, 109, 110])

In [123]:
arr * 100

array([1000, 1000, 1000, 1000, 1000, 1000,  600,  700,  800,  900, 1000])

In [124]:
arr / 100

array([0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.1 , 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [0]:
#1/0

In [126]:
arr/arr #gives warning gives "nan" for 0/0 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [127]:
1/arr # 1/0 gives inf

array([0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
       0.1       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [128]:
arr **  2

array([100, 100, 100, 100, 100, 100,  36,  49,  64,  81, 100])

#Universal Array Operations

In [129]:
np.sqrt(arr) #square root

array([3.16227766, 3.16227766, 3.16227766, 3.16227766, 3.16227766,
       3.16227766, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [130]:
np.exp(arr) #e**arr

array([22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481,
       22026.46579481, 22026.46579481,   403.42879349,  1096.63315843,
        2980.95798704,  8103.08392758, 22026.46579481])

In [131]:
np.max(arr)

10

In [132]:
arr.max()

10

In [133]:
np.sin(arr)

array([-0.54402111, -0.54402111, -0.54402111, -0.54402111, -0.54402111,
       -0.54402111, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [134]:
np.log(arr) #log0 = negative infinity

array([2.30258509, 2.30258509, 2.30258509, 2.30258509, 2.30258509,
       2.30258509, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [135]:
arr.reshape(11,1)

array([[10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [136]:
arr.sum(axis=0) #axis = 0 is for column sums

100